---
services:
  redis:
    image: redis:alpine
    env_file:
      - ../env/databases/redis.env
    networks:
      - dev
      - test
      - stage
      - prod
  postgres:
    image: postgres:14.1-alpine
    env_file:
      - ../env/databases/postgres.env
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    networks:
      - dev
      - test
      - stage
      - prod
