---
services:
  redis:
    image: redis:alpine
    networks:
      - dev
      - test
      - stage
      - prod
  postgres:
    image: postgres:14
    networks:
      - dev
      - test
      - stage
      - prod
