---
services:
  frontend:
    image: frontend:dev
    env_file:
      - ../../env/frontend/development.env
    build:
      context: ../../contexts/frontend
      dockerfile: ../../docker-appliance/dockerfiles/frontend.Dockerfile
      target: development
    entrypoint: "/usr/local/sbin/entrypoint"
    networks:
      - dev
  backend:
    image: backend:dev
    env_file:
      - ../../env/backend/development.env
      - ../../env/databases/postgres.env
      - ../../env/databases/redis.env
    build:
      context: ../../contexts/backend
      dockerfile: ../../docker-appliance/dockerfiles/backend.Dockerfile
      target: development
    entrypoint: "/usr/local/sbin/entrypoint"
    networks:
      - dev
