---
services:
  frontend:
    image: frontend:latest
    env_file:
      - ../env/prod.env
      - ../env/storage.env
    build:
      context: ../../apps/frontend/
      dockerfile: ../dockerfiles/frontend.Dockerfile
      target: production
    entrypoint: ["sbin", "frontend_prod"]
    networks:
      - prod
  backend:
    image: backend:latest
    env_file:
      - ../env/prod.env
      - ../env/storage.env
    build:
      context: ../../apps/backend/
      dockerfile: ../dockerfiles/backend.Dockerfile
      target: production
    entrypoint: ["sbin", "backend_prod"]
    networks:
      - prod
