---
services:
  frontend:
    image: frontend:latest
    env_file:
      - ../../env/frontend/production.env
    build:
      context: ../../contexts/frontend/
      dockerfile: ../../docker-appliance/dockerfiles/frontend.Dockerfile
      target: production
    entrypoint: ["sbin", "frontend_prod"]
    networks:
      - prod
  backend:
    image: backend:latest
    env_file:
      - ../../env/backend/production.env
      - ../../env/databases/postgres.env
      - ../../env/databases/redis.env
    build:
      context: ../../contexts/backend/
      dockerfile: ../../docker-appliance/dockerfiles/backend.Dockerfile
      target: production
    entrypoint: ["sbin", "backend_prod"]
    networks:
      - prod
