---
services:
  frontend:
    image: frontend:test
    env_file:
      - ../../env/frontend/test.env
    build:
      context: ../../contexts/frontend/
      dockerfile: ../../docker-appliance/dockerfiles/frontend.Dockerfile
      target: test
    entrypoint: ["sbin", "frontend_test"]
    networks:
      - test
  backend:
    image: backend:test
    env_file:
      - ../../env/backend/test.env
      - ../../env/databases/postgres.env
      - ../../env/databases/redis.env
    build:
      context: ../../contexts/backend/
      dockerfile: ../../docker-appliance/dockerfiles/backend.Dockerfile
      target: test
    entrypoint: ["sbin", "backend_test"]
    networks:
      - test
